config/routes.rb
Rails.application.routes.draw do
  resources :stops
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'routes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/route.rb
class Route < ApplicationRecord
  include Filterable
  mount_uploader :file, AttachmentUploader

  after_create :delay_import_data, if: Proc.new{|r| r.callback?}

  has_many :stops, inverse_of: :route, dependent: :destroy

  validates :name_load, :date, presence: true
  validates :route, uniqueness: {message: 'Esta ruta ya existe'}

  scope :by_name_load, -> (nload) { where(name_load: nload)}
  scope :by_date, -> (date) { where(date: date)}
  scope :by_hour_start, -> (hstart) { where(hour_start: hstart)}

  def import
    file = self.file
    sheet = Roo::CSV.new(file.path)
    (2..sheet.last_row).each do |row|
      if sheet.cell(row-1,1) && sheet.cell(row-1,2) && sheet.cell(row-1,3) && sheet.cell(row-1,4) && sheet.cell(row-1,5)
        if row == 2
          if self.update(route: sheet.cell(row,1))
            stop = Stop.create(
              route: self,
              hour_arrival: sheet.cell(row,2),
              load: sheet.cell(row,3),
              latitude: sheet.cell(row,4),
              longitude: sheet.cell(row,5)
            )
          else
            self.destroy
          end
        elsif Route.find_by(route: sheet.cell(row,1)).present?
          route = Route.find_by(route: sheet.cell(row,1))
          stop = Stop.create(
            route: route,
            hour_arrival: sheet.cell(row,2),
            load: sheet.cell(row,3),
            latitude: sheet.cell(row,4),
            longitude: sheet.cell(row,5)
          )
        elsif sheet.cell(row,1).present?
          new_route = Route.new(
            route: sheet.cell(row,1),
            name_load: name_load,
            date: date,
            callback: false
          )
          if new_route.save
            stop = Stop.create(
              route: new_route,
              hour_arrival: sheet.cell(row,2),
              load: sheet.cell(row,3),
              latitude: sheet.cell(row,4),
              longitude: sheet.cell(row,5)
            )
          end
        end
      end
    end
  end

  private

  def delay_import_data
    self.delay(queue: 'import_data').import
  end
end

app/models/stop.rb
class Stop < ApplicationRecord
  after_create :set_hour, if: Proc.new{|s| s.route.stops.count > 1}

  belongs_to :route

  validates :hour_arrival, :load, :latitude, :longitude, presence: true

  def set_hour
    hour_start = self.route.stops.collect(&:hour_arrival).min
    hour_end = self.route.stops.collect(&:hour_arrival).max
    self.route.update(hour_start: hour_start, hour_end: hour_end)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
    @routes = @routes.page params[:page]
    @routes = @routes.filter(params.slice(
      :by_name_load, :by_date, :by_hour_start
      ))
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)
    respond_to do |format|
      if @route.save
        format.html { redirect_to routes_path, notice: 'Ruta creada con exito.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name_load, :route, :date, :hour_start, :hour_end, :file)
    end
end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  before_action :set_stop, only: [:show, :edit, :update, :destroy]

  # GET /stops
  # GET /stops.json
  def index
    @stops = Stop.all
  end

  # GET /stops/1
  # GET /stops/1.json
  def show
  end

  # GET /stops/new
  def new
    @stop = Stop.new
  end

  # GET /stops/1/edit
  def edit
  end

  # POST /stops
  # POST /stops.json
  def create
    @stop = Stop.new(stop_params)

    respond_to do |format|
      if @stop.save
        format.html { redirect_to @stop, notice: 'Stop was successfully created.' }
        format.json { render :show, status: :created, location: @stop }
      else
        format.html { render :new }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stops/1
  # PATCH/PUT /stops/1.json
  def update
    respond_to do |format|
      if @stop.update(stop_params)
        format.html { redirect_to @stop, notice: 'Stop was successfully updated.' }
        format.json { render :show, status: :ok, location: @stop }
      else
        format.html { render :edit }
        format.json { render json: @stop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stops/1
  # DELETE /stops/1.json
  def destroy
    @stop.destroy
    respond_to do |format|
      format.html { redirect_to stops_url, notice: 'Stop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stop
      @stop = Stop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stop_params
      params.require(:stop).permit(:route_id, :hour_arrival, :load, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stops_helper.rb
module StopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaRouting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name_load %>
    <%= form.text_field :name_load %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label "File" %>
    <%= form.file_field :file, multiple: false, required: true %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header clearfix">
  <h3>Rutas</h3>
</div>

<div class="panel panel-default" id="table_routes">
  <div class="panel-heading clearfix">
    <%= form_tag routes_path+"#tabla", method: 'get' do%>
      <div class="row">
        <div class="col-md-2">
          <%=label_tag "Nombre de Carga"%>
          <%=text_field_tag("by_name_load", value = nil, options = {class: "form-control input-height"}) %>
        </div>
        <div class="col-md-2">
          <%=label_tag "Fecha"%>
          <%=date_field_tag("by_date", value = nil, options = {class: "form-control input-height",min: 0}) %>
        </div>
        <div class="col-md-2">
        <%=label_tag "Hora de Inicio"%>
        <%=text_field_tag('by_hour_start', value = nil, options = {class: "form-control input-height",min: 0})%>
        </div>
      </div><!-- /.row -->
      <div class="row">
        <div class="col-md-12">
          <div class=" botones">
            <%=button_tag(type: "submit",class: "btn btn-info") do%>
              <%= fa_icon 'filter', text:'Filtrar'%>
            <%end%>
            <%=link_to :back,class: "btn btn-warning" do%>
              <%= fa_icon 'trash-o', text: 'Limpiar' %>
            <%end%>

          </div>
        </div>
      </div>
    <%end%>
  </div>
  <div class="panel-body">

      <div class="table-responsive">
        <table class="table table-striped table-hover">
          <thead>

          <tr class="pretty">
            <th>Nombre de Carga</th>
            <th>Ruta</th>
            <th>Fecha</th>
            <th>Hora de inicio</th>
            <th>Hora de fin</th>
            <th colspan="3"></th>
          </tr>
          </thead>

          <tbody>
            <% @routes.each do |route| %>
              <tr>
                <td><%= route.name_load %></td>
                <td><%= route.route %></td>
                <td><%= route.date %></td>
                <td><%= route.hour_start %></td>
                <td><%= route.hour_end %></td>
                <td><%= link_to 'Show', route %></td>
                <td><%= link_to 'Edit', edit_route_path(route) %></td>
                <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

  </div>
</div>

<br>

<%= link_to 'Cargar Rutas', new_route_path %>

app/views/routes/new.html.erb
<h1>Cargar Rutas</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel-body">
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="cabecera">
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <tbody>
          <tr>
            <td class="active">Nombre de Carga</td>
            <td><%= @route&.name_load %></td>
          </tr>
          <tr>
            <td class="active">Ruta</td>
            <td><%= @route&.route %></td>
          </tr>
          <tr>
            <td class="active">Fecha</td>
            <td><%= @route&.date %></td>
          </tr>
          <tr>
            <td class="active">Hora de Inicio</td>
            <td><%= @route&.hour_start %></td>
          </tr>
          <tr>
            <td class="active">Hora de Fin</td>
            <td><%= @route&.hour_end %></td>
          </tr>
      </tbody>
    </table>

    <table class="table table-bordered table-striped">
      <thead>
        <th>Paradas</th>
        <th colspan="2"></th>
      </thead>
      <tbody>
        <% @route.stops.each do |stop| %>
          <tr>
            <td class="active">Hora de Llegada: <%= stop&.hour_arrival %></td>
            <td class="active">Carga: <%= stop&.load %></td>
          </tr>
          <tr>
            <td class="active">Latitud: <%= stop&.latitude %></td>
            <td class="active">longitude: <%= stop&.longitude %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

</div>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/stops/_form.html.erb
<%= form_with(model: stop, local: true) do |form| %>
  <% if stop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stop.errors.count, "error") %> prohibited this stop from being saved:</h2>

      <ul>
      <% stop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :route_id %>
    <%= form.text_field :route_id %>
  </div>

  <div class="field">
    <%= form.label :hour_arrival %>
    <%= form.text_field :hour_arrival %>
  </div>

  <div class="field">
    <%= form.label :load %>
    <%= form.number_field :load %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stops/edit.html.erb
<h1>Editing Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Show', @stop %> |
<%= link_to 'Back', stops_path %>

app/views/stops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stops</h1>

<table>
  <thead>
    <tr>
      <th>Route</th>
      <th>Hour arrival</th>
      <th>Load</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stops.each do |stop| %>
      <tr>
        <td><%= stop.route %></td>
        <td><%= stop.hour_arrival %></td>
        <td><%= stop.load %></td>
        <td><%= stop.latitude %></td>
        <td><%= stop.longitude %></td>
        <td><%= link_to 'Show', stop %></td>
        <td><%= link_to 'Edit', edit_stop_path(stop) %></td>
        <td><%= link_to 'Destroy', stop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stop', new_stop_path %>

app/views/stops/new.html.erb
<h1>New Stop</h1>

<%= render 'form', stop: @stop %>

<%= link_to 'Back', stops_path %>

app/views/stops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Route:</strong>
  <%= @stop.route %>
</p>

<p>
  <strong>Hour arrival:</strong>
  <%= @stop.hour_arrival %>
</p>

<p>
  <strong>Load:</strong>
  <%= @stop.load %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @stop.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @stop.longitude %>
</p>

<%= link_to 'Edit', edit_stop_path(@stop) %> |
<%= link_to 'Back', stops_path %>